name: Databases Cleanup
on:
  delete 
#  workflow_dispatch
  
jobs:
  delete_databases:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_BRANCH: ${{ github.ref }}
        run: |
          echo "${GITHUB_BRANCH##*/}"
          # curl -H "Content-Type: application/json" -X POST "http://faster-github-cdm-01-d71037c7dd406d80.elb.us-east-1.amazonaws.com/api/github/delete-databases?engine=MSSQL&cdmUsername=service.eng.faster&cdmPassword=nWp6kiHayp266L6jspnsRmyGk8bp2BAS6PMSaLIFf%2FBKFV%2Fhgrglb%2BL%2FikfnMogIWlqwEap7Hi366DyRWeTYsQE4qKv%2FEhBmFUWsguSX4iyfMbg0oZDRt8fLnHFWeHluR0FTq2LBE6ptHV3K7hDOzvpsynzyBOi1la1e9Q%2FDDrM%3D&cdmConnection=sql01qa&cdmProduct=Agemni&cdmEnvironment=Dev&startsWith=dagm&contains=AGEMNI_00007"
