name: Databases Cleanup
on:
  delete 
#  workflow_dispatch
  
jobs:
  cleanup-databases:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - env:
          DB_PREFIX: "dagm_"
          BRANCH_NAME: ${{ github.event.ref }}
          CDM_URL: "http://faster-github-cdm-01-d71037c7dd406d80.elb.us-east-1.amazonaws.com/api/github/delete-databases"
          CDM_USER: "servicecdm.agemni"
          CDM_TOKEN: "brR6%2BE0jo2SPzchVXj6YRVtBDqASGaiKWMXtBpr%2FwhMtGVxxXf%2FbujejLGbGi8RzZ3H7fskavuJyN%2FhAKFRsibhcTL02Yat%2Br%2B%2Bxs0e3zMJsKcMokz0CR%2FJIGkSPf8uxrxh10splvsCPqwu9ERv7hBvGiZWhwIyaZusnTalAyn8%3D"
          CDM_ENGINE: "MSSQL"
          CDM_CONNECTION: "sql01qa"
          CDM_PRODUCT: "Agemni"
          CDM_ENVIRONMENT: "Dev"
        run: |
          DB_IDENTIFIER="${BRANCH_NAME//-/_}"
          DB_IDENTIFIER="${DB_IDENTIFIER// /_}"
          DB_IDENTIFIER="${DB_IDENTIFIER//\//_}"
          
          curl -H "Content-Type: application/json" -X POST "${CDM_URL}?cdmUsername=${CDM_USER}&cdmPassword=${CDM_TOKEN}&engine=${CDM_ENGINE}&cdmConnection=${CDM_CONNECTION}&cdmProduct=${CDM_PRODUCT}&cdmEnvironment=${CDM_ENVIRONMENT}&startsWith=${DB_PREFIX}&contains=${DB_IDENTIFIER}"
